CREATE TABLE OperacaoAgricola (
  ID                         number(10) GENERATED AS IDENTITY, 
  TipoOperacaoTipo           varchar2(255) NOT NULL, 
  CadernoCampoID             number(10), 
  DataRealizacao             date NOT NULL, 
  Quantidade                 number(10), 
  Unidadedesignacao          varchar2(10), 
  FatorProducaoNomeComercial varchar2(255), 
  Parcela                    varchar2(255) NOT NULL, 
  Cultura                    varchar2(255) NOT NULL, 
  PRIMARY KEY (ID));

INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2017',  0.4,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2017',  0.9,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2017',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2017',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2017',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2017',  0.4,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2017',  0.9,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2017',  3.5,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2017',  3.5,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2017',  3.5,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Sep-2017',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Sep-2017',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Sep-2017',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '04-Nov-2017',  30.0,  'un',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '04-Nov-2017',  20.0,  'un',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '10-Dec-2017',  15.0,  'kg',  'Patentkali',  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '10-Dec-2017',  10.0,  'kg',  'Patentkali',  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '07-Jan-2018',  90.0,  'un',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '08-Jan-2018',  60.0,  'un',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '08-Jan-2018',  40.0,  'un',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '06-Feb-2018',  10.0,  'kg',  'Esta kieserit',  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '06-Feb-2018',  6.0,  'kg',  'Esta kieserit',  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '06-Feb-2018',  5.0,  'kg',  'Esta kieserit',  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2018',  1.0,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2018',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2018',  3.5,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2018',  3.5,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2018',  3.5,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2018',  6.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2018',  1.0,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2018',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '11-Aug-2018',  7.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '02-Sep-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '02-Sep-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '02-Sep-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Sep-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Sep-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Sep-2018',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '17-Nov-2018',  30.0,  'un',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '17-Nov-2018',  20.0,  'un',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Plantação', 1,  '10-Dec-2018',  30.0,  'un',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '16-Dec-2018',  500.0,  'un',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '07-Jan-2019',  90.0,  'un',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '08-Jan-2019',  60.0,  'un',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '08-Jan-2019',  40.0,  'un',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Aplicação fitofármaco', 1,  '20-Jan-2019',  2.0,  'kg',  'Calda bordalesa ascenza',  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '06-Feb-2019',  10.0,  'kg',  'Esta kieserit',  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '06-Feb-2019',  5.0,  'kg',  'Esta kieserit',  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '06-Feb-2019',  7.0,  'kg',  'Esta kieserit',  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2019',  1.0,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2019',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2019',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2019',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2019',  4.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2019',  6.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2019',  1.0,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2019',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2019',  4.5,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2019',  4.5,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2019',  4.5,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '11-Aug-2019',  7.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '15-Nov-2019',  30.0,  'un',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '15-Nov-2019',  20.0,  'un',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '16-Dec-2019',  500.0,  'un',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Aplicação fitofármaco', 1,  '20-Jan-2020',  2.0,  'kg',  'Calda bordalesa ascenza',  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Sementeira', 1,  '12-Mar-2020',  0.9,  'kg',  null,  'Horta nova', 'Cenoura scarlet nantes');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '05-May-2020',  2200.0,  'kg',  null,  'Horta nova', 'Cenoura scarlet nantes');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-May-2020',  1400.0,  'kg',  null,  'Horta nova', 'Cenoura scarlet nantes');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2020',  1.0,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2020',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2020',  6.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '12-Jul-2020',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '15-Jul-2020',  2.5,  'm3',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '28-Jul-2020',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2020',  1.0,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2020',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2020',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '11-Aug-2020',  7.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '12-Aug-2020',  3.5,  'm3',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '20-Aug-2020',  3300.0,  'kg',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '28-Aug-2020',  600.0,  'kg',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '07-Sep-2020',  1800.0,  'kg',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '10-Nov-2020',  30.0,  'un',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '10-Nov-2020',  20.0,  'un',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-Nov-2020',  600.0,  'kg',  null,  'Horta nova', 'Nabo s. cosme');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '05-Dec-2020',  70.0,  'un',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '05-Dec-2020',  50.0,  'un',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '10-Dec-2020',  10.0,  'kg',  'Patentkali',  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '10-Dec-2020',  7.0,  'kg',  'Patentkali',  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '15-Dec-2020',  40.0,  'un',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '15-Dec-2020',  60.0,  'un',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '16-Dec-2020',  500.0,  'un',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '18-Dec-2020',  2500.0,  'kg',  null,  'Horta nova', 'Nabo s. cosme');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '04-Jan-2021',  2900.0,  'kg',  null,  'Horta nova', 'Nabo s. cosme');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Aplicação fitofármaco', 1,  '20-Jan-2021',  2.0,  'kg',  'Calda bordalesa ascenza',  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Incorporação no solo', 1,  '14-Mar-2021',  1.3,  'ha',  null,  'Campo do poço', 'Tremoço amarelo');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Incorporação no solo', 1,  '30-Mar-2021',  1.3,  'ha',  null,  'Campo da bouça', 'Tremoço amarelo');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Sementeira', 1,  '15-Apr-2021',  30.0,  'kg',  null,  'Campo da bouça', 'Milho doce golden bantam');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '02-May-2021',  10.0,  'kg',  'Epso microtop',  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '02-May-2021',  10.0,  'kg',  'Epso microtop',  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '02-May-2021',  10.0,  'kg',  'Epso microtop',  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '05-May-2021',  2200.0,  'kg',  null,  'Horta nova', 'Cenoura sugarsnax hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-May-2021',  1400.0,  'kg',  null,  'Horta nova', 'Cenoura sugarsnax hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '20-Jun-2021',  3.0,  'm3',  null,  'Horta nova', 'Cenoura danvers half long');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2021',  0.8,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2021',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '05-Jul-2021',  5.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '05-Jul-2021',  5.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '05-Jul-2021',  5.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '07-Jul-2021',  3.0,  'm3',  null,  'Horta nova', 'Cenoura danvers half long');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Jul-2021',  7.0,  'm3',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '12-Jul-2021',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-Jul-2021',  300.0,  'kg',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '20-Jul-2021',  400.0,  'kg',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '24-Jul-2021',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2021',  5.5,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2021',  5.5,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2021',  5.5,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2021',  3.5,  'm3',  null,  'Horta nova', 'Cenoura danvers half long');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '07-Aug-2021',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2021',  0.8,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2021',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '12-Aug-2021',  3300.0,  'kg',  null,  'Campo da bouça', 'Milho doce golden bantam');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '17-Aug-2021',  3.0,  'm3',  null,  'Horta nova', 'Cenoura danvers half long');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '24-Aug-2021',  900.0,  'kg',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '25-Aug-2021',  3300.0,  'kg',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '28-Aug-2021',  600.0,  'kg',  null,  'Horta nova', 'Cenoura danvers half long');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '05-Sep-2021',  800.0,  'kg',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '07-Sep-2021',  1800.0,  'kg',  null,  'Horta nova', 'Cenoura danvers half long');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '12-Sep-2021',  800.0,  'kg',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '23-Sep-2021',  1200.0,  'kg',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '12-Oct-2021',  950.0,  'kg',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '03-Nov-2021',  750.0,  'kg',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '10-Nov-2021',  210.0,  'kg',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '10-Nov-2021',  120.0,  'kg',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-Nov-2021',  600.0,  'kg',  null,  'Horta nova', 'Nabo s. cosme');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '17-Nov-2021',  30.0,  'un',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '17-Nov-2021',  20.0,  'un',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '28-Nov-2021',  70.0,  'un',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '03-Dec-2021',  90.0,  'un',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '16-Dec-2021',  500.0,  'un',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '18-Dec-2021',  60.0,  'un',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '18-Dec-2021',  2500.0,  'kg',  null,  'Horta nova', 'Nabo s. cosme');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '04-Jan-2022',  2900.0,  'kg',  null,  'Horta nova', 'Nabo s. cosme');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Aplicação fitofármaco', 1,  '20-Jan-2022',  3.0,  'kg',  'Calda bordalesa ascenza',  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Incorporação no solo', 1,  '19-Mar-2022',  1.3,  'ha',  null,  'Campo do poço', 'Tremoço amarelo');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Incorporação no solo', 1,  '05-Apr-2022',  1.3,  'ha',  null,  'Campo da bouça', 'Tremoço amarelo');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '05-May-2022',  2250.0,  'kg',  null,  'Horta nova', 'Cenoura sugarsnax hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '13-May-2022',  10.0,  'kg',  'Epso microtop',  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '13-May-2022',  10.0,  'kg',  'Epso microtop',  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '13-May-2022',  10.0,  'kg',  'Epso microtop',  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-May-2022',  1300.0,  'kg',  null,  'Horta nova', 'Cenoura sugarsnax hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '05-Jun-2022',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '05-Jun-2022',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '05-Jun-2022',  3.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jun-2022',  3.0,  'm3',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '02-Jul-2022',  5.5,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '02-Jul-2022',  5.5,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '02-Jul-2022',  5.5,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2022',  0.8,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '03-Jul-2022',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '12-Jul-2022',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '15-Jul-2022',  3.0,  'm3',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-Jul-2022',  600.0,  'kg',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '20-Jul-2022',  500.0,  'kg',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '24-Jul-2022',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2022',  5.0,  'm3',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2022',  5.0,  'm3',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2022',  5.0,  'm3',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '30-Jul-2022',  2.5,  'm3',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '07-Aug-2022',  15.0,  'm3',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2022',  0.8,  'm3',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '10-Aug-2022',  1.5,  'm3',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '17-Aug-2022',  3500.0,  'kg',  null,  'Campo da bouça', 'Milho doce golden bantam');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Rega', 1,  '17-Aug-2022',  3.0,  'm3',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '18-Aug-2022',  3300.0,  'kg',  null,  'Campo do poço', 'Milho mas 24.c');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '20-Aug-2022',  950.0,  'kg',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '24-Aug-2022',  650.0,  'kg',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '05-Sep-2022',  1900.0,  'kg',  null,  'Horta nova', 'Cenoura nelson hybrid');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '07-Sep-2022',  830.0,  'kg',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '11-Sep-2022',  750.0,  'kg',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '20-Sep-2022',  1150.0,  'kg',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '17-Oct-2022',  850.0,  'kg',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '06-Nov-2022',  900.0,  'kg',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '10-Nov-2022',  30.0,  'un',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '10-Nov-2022',  20.0,  'un',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '12-Nov-2022',  300.0,  'kg',  null,  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '12-Nov-2022',  200.0,  'kg',  null,  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '15-Nov-2022',  50.0,  'kg',  null,  'Horta nova', 'Nabo greleiro senhora conceição');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '04-Dec-2022',  70.0,  'un',  null,  'Lameiro da ponte', 'Macieira royal gala');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '07-Dec-2022',  90.0,  'un',  null,  'Lameiro da ponte', 'Macieira jonagored');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '11-Dec-2022',  15.0,  'kg',  'Patentkali',  'Campo grande', 'Oliveira galega');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Fertilização', 1,  '11-Dec-2022',  10.0,  'kg',  'Patentkali',  'Campo grande', 'Oliveira picual');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '16-Dec-2022',  500.0,  'un',  null,  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '18-Dec-2022',  200.0,  'kg',  null,  'Horta nova', 'Nabo greleiro senhora conceição');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Poda', 1,  '12-Jan-2023',  60.0,  'un',  null,  'Lameiro da ponte', 'Macieira fuji');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Colheita', 1,  '14-Jan-2023',  250.0,  'kg',  null,  'Horta nova', 'Nabo greleiro senhora conceição');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Aplicação fitofármaco', 1,  '20-Jan-2023',  4.0,  'kg',  'Calda bordalesa ascenza',  'Vinha', 'Videira dona maria');
INSERT INTO operacaoagricola(tipooperacaotipo, cadernocampoid, datarealizacao, quantidade, unidadedesignacao, FatorProducaoNomeComercial, parcela, cultura) VALUES( 'Incorporação no solo', 1,  '20-Mar-2023',  1.3,  'ha',  null,  'Campo do poço', 'Tremoço amarelo');

SELECT 
    parcela AS "Nome da Parcela",
    cultura AS "Nome da Cultura",
    SUM(Quantidade) AS "Quantidade Colhida"
FROM 
    operacaoagricola
WHERE
    datarealizacao BETWEEN '01-Jan-2017' AND '30-Dec-2023'
    AND parcela = 'Campo grande'
    AND tipooperacaotipo='Colheita' 
GROUP BY
    parcela,
    cultura;

