SELECT
    OperacaoAgricola.parcela AS Parcela,
    FATORPRODUCAO_TIPO.TIPOFATORPRODUCAOTIPO AS TipoFatorProdução,
    COUNT(OperacaoAgricola.FATORPRODUCAONOMECOMERCIAL) AS NumeroDeFatoresDeProducao
FROM OPERACAOAGRICOLA
         INNER JOIN FATORPRODUCAO_TIPO ON OperacaoAgricola.FATORPRODUCAONOMECOMERCIAL = FATORPRODUCAO_TIPO.FATORPRODUCAONOMECOMERCIAL
WHERE OperacaoAgricola.parcela = 'Lameiro da ponte'
  AND OperacaoAgricola.DATAREALIZACAO  BETWEEN TO_DATE('02-Jul-2017', 'DD-Mon-YYYY') AND TO_DATE('10-Sep-2019', 'DD-Mon-YYYY')
GROUP BY OperacaoAgricola.parcela, FATORPRODUCAO_TIPO.TIPOFATORPRODUCAOTIPO;
